services:
  mural-k:
    image: katzzero/mural-k
    # or: image: ghcr.io/katzzero/mural-k
    container_name: mural-k
    ports:
      - "8080:5000"
    volumes:
      - mural-k-data:/data
    restart: unless-stopped

volumes:
  mural-k-data:
